# Generated by Django 5.2.11 on 2026-02-08 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(choices=[('YAMAHA', 'Yamaha'), ('HONDA', 'Honda'), ('SUZUKI', 'Suzuki'), ('KAWASAKI', 'Kawasaki'), ('DUCATI', 'Ducati'), ('BMW', 'BMW'), ('AUTRE', 'Autre')], max_length=20)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('kilometrage', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_moto', models.CharField(choices=[('SPORT', 'Sportive'), ('ROADSTER', 'Roadster'), ('CUSTOM', 'Custom'), ('ENDURO', 'Enduro'), ('SCOOTER', 'Scooter'), ('GT', 'Grand Tourisme')], max_length=20)),
                ('couleur', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('vendu', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acheteur_nom', models.CharField(max_length=100)),
                ('acheteur_email', models.EmailField(max_length=254)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motos.moto')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motos.vendeur')),
            ],
        ),
    ]
