# Generated by Django 5.2.11 on 2026-02-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto',
            name='image_url',
        ),
        migrations.AddField(
            model_name='moto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='motos_image/'),
        ),
    ]
